/**
 * Stable error codes shared by the background pipeline and the UI.
 * `USER_ERROR_MESSAGES` is the only place where user-facing wording lives,
 * so the UI never renders raw exceptions or stack traces.
 */
export const ErrorCode = {
  BAD_MESSAGE: 'BAD_MESSAGE',
  UNKNOWN_MESSAGE: 'UNKNOWN_MESSAGE',
  UNAUTHORIZED_SENDER: 'UNAUTHORIZED_SENDER',
  INVALID_PAYLOAD: 'INVALID_PAYLOAD',
  EMPTY_COMMAND: 'EMPTY_COMMAND',
  INVALID_SETTINGS: 'INVALID_SETTINGS',
  PAGE_UNAVAILABLE: 'PAGE_UNAVAILABLE',
  EXTENSION_ACTION_UNAVAILABLE: 'EXTENSION_ACTION_UNAVAILABLE',
  AI_UNAVAILABLE: 'AI_UNAVAILABLE',
  AI_TIMEOUT: 'AI_TIMEOUT',
  AI_RATE_LIMITED: 'AI_RATE_LIMITED',
  AI_AUTH_ERROR: 'AI_AUTH_ERROR',
  AI_INVALID_RESPONSE: 'AI_INVALID_RESPONSE',
  AI_INVALID_REQUEST: 'AI_INVALID_REQUEST',
  AI_CONTEXT_TOO_LARGE: 'AI_CONTEXT_TOO_LARGE',
  AI_NETWORK_ERROR: 'AI_NETWORK_ERROR',
  AI_PROVIDER_ERROR: 'AI_PROVIDER_ERROR',
  AI_CONFIGURATION_ERROR: 'AI_CONFIGURATION_ERROR',
  AI_PAGE_UNAVAILABLE: 'AI_PAGE_UNAVAILABLE',
  AI_CANCELLED: 'AI_CANCELLED',
  ACTION_INVALID: 'ACTION_INVALID',
  ACTION_NOT_ALLOWED: 'ACTION_NOT_ALLOWED',
  ACTION_PERMISSION_REQUIRED: 'ACTION_PERMISSION_REQUIRED',
  ACTION_PERMISSION_DENIED: 'ACTION_PERMISSION_DENIED',
  ACTION_PERMISSION_EXPIRED: 'ACTION_PERMISSION_EXPIRED',
  ACTION_PLAN_CHANGED: 'ACTION_PLAN_CHANGED',
  ACTION_PLAN_UNKNOWN: 'ACTION_PLAN_UNKNOWN',
  ACTION_CONTEXT_STALE: 'ACTION_CONTEXT_STALE',
  ACTION_TARGET_NOT_FOUND: 'ACTION_TARGET_NOT_FOUND',
  ACTION_TARGET_AMBIGUOUS: 'ACTION_TARGET_AMBIGUOUS',
  ACTION_SENSITIVE_FIELD: 'ACTION_SENSITIVE_FIELD',
  ACTION_EXECUTION_FAILED: 'ACTION_EXECUTION_FAILED',
  ACTION_VERIFICATION_FAILED: 'ACTION_VERIFICATION_FAILED',
  ACTION_LIMIT_EXCEEDED: 'ACTION_LIMIT_EXCEEDED',
  ACTION_TIMEOUT: 'ACTION_TIMEOUT',
  ACTION_CANCELLED: 'ACTION_CANCELLED',
  ACTION_UNSUPPORTED: 'ACTION_UNSUPPORTED',
  UNEXPECTED_ERROR: 'UNEXPECTED_ERROR',
} as const;

export type ErrorCode = (typeof ErrorCode)[keyof typeof ErrorCode];

export const USER_ERROR_MESSAGES: Record<ErrorCode, string> = {
  BAD_MESSAGE: 'The message received was not valid.',
  UNKNOWN_MESSAGE: 'Unknown message type.',
  UNAUTHORIZED_SENDER: 'This request was not allowed.',
  INVALID_PAYLOAD: 'The request contained invalid data.',
  EMPTY_COMMAND: 'Enter a command first.',
  INVALID_SETTINGS: 'The settings change was not valid.',
  PAGE_UNAVAILABLE: 'No page context is available right now.',
  EXTENSION_ACTION_UNAVAILABLE:
    'This feature is only available when CommandLayer is loaded as a browser extension.',
  AI_UNAVAILABLE: 'Intelligence is unavailable right now.',
  AI_TIMEOUT: 'The request took too long. Please try again.',
  AI_RATE_LIMITED: 'Too many requests. Please wait a moment and try again.',
  AI_AUTH_ERROR: 'The AI service rejected the connection. Check your gateway configuration.',
  AI_INVALID_RESPONSE: 'The AI service returned an unexpected response.',
  AI_INVALID_REQUEST: 'That request could not be understood. Please rephrase it.',
  AI_CONTEXT_TOO_LARGE: 'This page is too large to analyze right now.',
  AI_NETWORK_ERROR: 'Could not reach the AI service. Check your connection.',
  AI_PROVIDER_ERROR: 'The AI service encountered an error.',
  AI_CONFIGURATION_ERROR: 'The AI service is not configured correctly.',
  AI_PAGE_UNAVAILABLE: 'Page contents are not available to reason about. Open a regular web page and try again.',
  AI_CANCELLED: 'This request was replaced by a newer one.',
  ACTION_INVALID: 'That action is not valid.',
  ACTION_NOT_ALLOWED: 'That action is not allowed.',
  ACTION_PERMISSION_REQUIRED: 'This action needs your explicit approval first.',
  ACTION_PERMISSION_DENIED: 'The action was not approved.',
  ACTION_PERMISSION_EXPIRED: 'The approval expired. Please review the plan again.',
  ACTION_PLAN_CHANGED: 'The plan changed after approval. Please review it again.',
  ACTION_PLAN_UNKNOWN: 'This plan is no longer available.',
  ACTION_CONTEXT_STALE: 'The page changed since this plan was created. Please try again.',
  ACTION_TARGET_NOT_FOUND: 'The target element could not be found on the page.',
  ACTION_TARGET_AMBIGUOUS: 'Several matching elements were found. Be more specific.',
  ACTION_SENSITIVE_FIELD: 'CommandLayer never types into sensitive fields such as passwords or payment details.',
  ACTION_EXECUTION_FAILED: 'The action could not be completed.',
  ACTION_VERIFICATION_FAILED: 'The action ran, but the result could not be verified.',
  ACTION_LIMIT_EXCEEDED: 'The requested action exceeds CommandLayer safety limits.',
  ACTION_TIMEOUT: 'The action took too long and was stopped.',
  ACTION_CANCELLED: 'The action was cancelled.',
  ACTION_UNSUPPORTED: 'That action is not supported in this version.',
  UNEXPECTED_ERROR: 'Something went wrong. Please try again.',
};
